version: "3.3"
services:
  reverseproxy:
    container_name: prod-ad-ssl-proxy
    image: nginx:1.23
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./production/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl/site.crt:/etc/ssl/certs/site.crt
      # - ./ssl/site.dec.key:/etc/ssl/private/site.dec.key
  nuxt:
    container_name: prod-ad-ssl-nuxt
    build:
      context: "nuxt"
      dockerfile: dev.Dockerfile
    volumes:
      - "./nuxt:/nuxt"
    restart: "on-failure:5"
    ports:
      - "3000:3000"
      - "24678:24678"
    environment:
      HOST: 0.0.0.0